[project]
name = "retracesoftware_autoenable"
version = "0.1.0"
license = {text = "Apache-2.0"}
dependencies = ["retracesoftware_proxy"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["sitecustomize"]