name: Build & Publish (Trusted Publisher)

on:
  workflow_dispatch:
  push:
    tags:
      - "autoenable-v*"

permissions:
  id-token: write
  contents: read

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules (recursive)
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive --remote

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify tag matches pyproject version
        run: |
          python - << 'PY'
          import os, tomllib
          tag = os.environ['GITHUB_REF_NAME'].split('autoenable-v', 1)[1]
          with open('pyproject.toml','rb') as f:
              version = tomllib.load(f)['project']['version']
          assert version == tag, f"version mismatch: tag={tag} pyproject={version}"
          print('version OK:', version)
          PY

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel

      - name: Smoke test wheel (no deps)
        run: |
          python -m pip install --force-reinstall --no-deps dist/*.whl
          python -c "import sitecustomize; print('ok')"

      - name: Publish to PyPI (Trusted Publisher)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
